### ISSUE TITLE
TripUpdatesFileWriter and VehiclePositionsFileWriter arguments

### ISSUE THREAD

**Issue by ktran9** [OneBusAway/onebusaway-gtfs-realtime-trip-updates-producer-demo#1]
Brian,

I tried to run your demo with all 4 arguments --tripUpdatesUrl (1), --vehiclePositionsUrl (2), --tripUpdatesPath (3), --vehiclePositionPath (4) but while the Servlets work perfectly, the 2 FileWriters don't output any files. Below are my arguments:

--tripUpdatesPath=C:\Test\tripUpdates.pb 
--vehiclePositionsPath=C:\Test\vehiclePositions.pb

The program gets into the if(cli.hasOption(ARG_TRIP_UPDATES_PATH) statement [line 94] in GtfsRealtimeTripUpdatesProducerDemoMain but seem like the writeMessageToFile() in AbstractGtfsRealtimeFileWriter doesn't get invoked. Could you please take a look to see if my args are okay? It may be best to give an example similar to --tripUpdatesUrl=http://localhost:8080/trip-updates and --vehiclePositionsUrl=http://localhost:8080/vehicle-positions

**Comment by bdferris** [comment]
I've made some changes that I think will help.  Can you try grabbing the latest source (or SNAPSHOT jar) and trying again?  Let me know if you still have trouble writing updates to file.

**Comment by ktran9** [comment]
Thanks. It's working now :)
